import{a as u,S as y,i as c}from"./assets/vendor-BK_rxH-O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();u.defaults.baseURL="https://pixabay.com/api/";const h="51662095-362d68f1fb432ef34c7441ea2";function b(r){return u.get("",{params:{key:h,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}})}let d,i;function L(r=[]){let o=document.querySelector("#gallery");o||(o=document.createElement("div"),o.id="gallery",o.classList.add("gallery"),document.body.appendChild(o));const s=r.map(({webformatURL:a,largeImageURL:e,tags:t,likes:n,views:m,comments:p,downloads:g})=>`
      <div class="photo-card">
        <a class="gallery__item" href="${e}">
          <img class="gallery__image" src="${a}" alt="${t}" loading="lazy" />
        </a>
        <ul class="info">
          <li><b>Likes:</b> ${n}</li>
          <li><b>Views:</b> ${m}</li>
          <li><b>Comments:</b> ${p}</li>
          <li><b>Downloads:</b> ${g}</li>
        </ul>
      </div>`).join("");o.insertAdjacentHTML("beforeend",s),d?d.refresh():d=new y("#gallery a",{captionsData:"alt",captionDelay:250})}function v(){const r=document.querySelector("#gallery");r&&(r.innerHTML="")}function x(){i||(i=document.createElement("div"),i.classList.add("loader","is-hidden"),i.innerHTML='<span class="loader__spinner"></span>',document.querySelector("form").insertAdjacentElement("afterend",i))}function E(){x(),i.classList.remove("is-hidden")}function S(){i&&i.classList.add("is-hidden")}const f=document.querySelector("form"),l=f.querySelector('button[type="submit"]');f.addEventListener("submit",r=>{r.preventDefault();const s=new FormData(r.target).get("searchText").trim();if(!s){c.error({position:"topRight",title:"Error",message:"Ви нічого не ввели!"});return}v(),E();const a=l.textContent;l.disabled=!0,b(s).then(e=>{const t=e.data.hits;if(!t.length){c.warning({position:"topRight",title:"Немає результатів",message:"Нічого не знайдено"}),l.disabled=!1,l.textContent=a;return}L(t)}).catch(e=>{console.log(e),c.error({position:"topRight",title:e,message:"Помилка"})}).then(()=>{S(),l.disabled=!1,r.target.reset()})});
//# sourceMappingURL=index.js.map
